services:
  backend:
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
